### ISSUE TITLE
What is Android 6 SDK needed for?

### ISSUE THREAD

**Issue by Avispa** [ElijaxApps-org/android-xmrig-miner#17]
Why resp. for what is Android 6 required?

Since it is basically a calculator app with even *less* basic user input than a calculator, shouldn't it run on Android 2.3? ;-)

Please lower the SDK setting/requirement.

**Comment by ElijaxApps** [comment]
Excuse me sir...

But I think Gingerbread is utterly outdated, even more than this miner.

I don't know how many hashes do you think you can achieve on Smartphones prior ICS. But not much xD

My last phone with Gingerbread died in 2014. I think it's time for you to update your hardware. :)

The Android 6 requirement was due to my target machine, a Galaxy Note 4. By the time the project was taken, there were nothing more updated: It was latest software.

The problem really here is the project have been unmantained while Android indeed have been, so, my fault. At first I did not think the impact of this android miner on miners ecosystem; it was morelike a test. 

Nowadays there are better miners suitable for android and smartphone devices, so keep in touck, as I'll release my own version of @shmulatov's VerusMiner900, fetauring tpruvot's ccminer. 

Cheers.
